import video1 from "../videos/video1.mp4";
import video2 from "../videos/video2.mp4";
import video3 from "../videos/video3.mp4";

export const listOfVideo = [
  {
    video_path: video1,
    video_id: 1,
    titre: "Top 5 capybara",
    user_id: "squewe",
    nb_vue: "713497",
    miniature: "https://i.ytimg.com/vi/ecTWwpRVc7k/maxresdefault.jpg",
  },
  {
    video_path: video2,
    video_id: 2,
    titre: "Top 5 monke",
    user_id: "squewe",
    nb_vue: "432008",
    miniature: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
  {
    video_path: video3,
    video_id: 3,
    titre: "Top 5 capybaras",
    user_id: "squewe",
    nb_vue: "1098734",
    miniature: "https://i.ytimg.com/vi/lJDL1O8xrLc/mqdefault.jpg",
  },
  {
    video_path: video2,
    video_id: 4,
    titre: "Top 5 monke",
    user_id: "squewe",
    nb_vue: "432008",
    miniature: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
  {
    video_path: video1,
    video_id: 5,
    titre: "Top 5 capybara",
    user_id: "squewe",
    nb_vue: "713497",
    miniature: "https://i.ytimg.com/vi/ecTWwpRVc7k/maxresdefault.jpg",
  },
  {
    video_path: video2,
    video_id: 6,
    titre: "Top 5 monke",
    user_id: "squewe",
    nb_vue: "432008",
    miniature: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
  {
    video_path: video3,
    video_id: 7,
    titre: "Top 5 capybaras",
    user_id: "squewe",
    nb_vue: "1098734",
    miniature: "https://i.ytimg.com/vi/lJDL1O8xrLc/mqdefault.jpg",
  },
  {
    video_path: video2,
    video_id: 8,
    titre: "Top 5 monke",
    user_id: "squewe",
    nb_vue: "432008",
    miniature: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
  {
    video_path: video1,
    video_id: 9,
    titre: "Top 5 capybara",
    user_id: "squewe",
    nb_vue: "713497",
    miniature: "https://i.ytimg.com/vi/ecTWwpRVc7k/maxresdefault.jpg",
  },
  {
    video_path: video2,
    video_id: 10,
    titre: "Top 5 monke",
    user_id: "squewe",
    nb_vue: "432008",
    miniature: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
];
