import video1 from "../videos/video1.mp4";
import video2 from "../videos/video2.mp4";
import video3 from "../videos/video3.mp4";

export const listOfVideo = [
  {
    video: video1,
    id: 1,
    title: "Top 5 capybara",
    creator: "squewe",
    nbView: "713497",
    poster: "https://i.ytimg.com/vi/ecTWwpRVc7k/maxresdefault.jpg",
  },
  {
    video: video2,
    id: 2,
    title: "Top 5 monke",
    creator: "squewe",
    nbView: "432008",
    poster: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
  {
    video: video3,
    id: 3,
    title: "Top 5 capybaras",
    creator: "squewe",
    nbView: "1098734",
    poster: "https://i.ytimg.com/vi/lJDL1O8xrLc/mqdefault.jpg",
  },
  {
    video: video2,
    id: 4,
    title: "Top 5 monke",
    creator: "squewe",
    nbView: "432008",
    poster: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
  {
    video: video1,
    id: 5,
    title: "Top 5 capybara",
    creator: "squewe",
    nbView: "713497",
    poster: "https://i.ytimg.com/vi/ecTWwpRVc7k/maxresdefault.jpg",
  },
  {
    video: video2,
    id: 6,
    title: "Top 5 monke",
    creator: "squewe",
    nbView: "432008",
    poster: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
  {
    video: video3,
    id: 7,
    title: "Top 5 capybaras",
    creator: "squewe",
    nbView: "1098734",
    poster: "https://i.ytimg.com/vi/lJDL1O8xrLc/mqdefault.jpg",
  },
  {
    video: video2,
    id: 8,
    title: "Top 5 monke",
    creator: "squewe",
    nbView: "432008",
    poster: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
  {
    video: video1,
    id: 9,
    title: "Top 5 capybara",
    creator: "squewe",
    nbView: "713497",
    poster: "https://i.ytimg.com/vi/ecTWwpRVc7k/maxresdefault.jpg",
  },
  {
    video: video2,
    id: 10,
    title: "Top 5 monke",
    creator: "squewe",
    nbView: "432008",
    poster: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
  {
    video: video3,
    id: 11,
    title: "Top 5 capybaras",
    creator: "squewe",
    nbView: "1098734",
    poster: "https://i.ytimg.com/vi/lJDL1O8xrLc/mqdefault.jpg",
  },
  {
    video: video2,
    id: 12,
    title: "Top 5 monke",
    creator: "squewe",
    nbView: "432008",
    poster: "https://i.ytimg.com/vi/1m5l3_7wu3M/maxresdefault.jpg",
  },
];
